name: Node.js CI Backend

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: Build Backend
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.14.0]

    env:
      MONGO: ${{ secrets.MONGO }}
      JWT: ${{ secrets.JWT }}

    steps:
      # Checkout the code from GitHub repository
      - uses: actions/checkout@v4

      # Set up Node.js with the specified version
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

#      # Stop pm2
#      - name: Stop pm2
#        run: |
#          pm2 stop 1

      # Install dependencies in the backend directory
      - name: Install Dependencies
        run: |
          npm ci

      # Delete existing .env file from backend production directory
      - name: Remove old .env file from backend
        run: |
          rm -f /home/janitha/production/backend/.env

      # Set up environmental variables
      - name: Add Environmental Variables
        run: |
          touch .env
          echo "MONGO=${{ secrets.MONGO }}" >> .env
          echo "JWT=${{ secrets.JWT }}" >> .env
#
#      - name: Restart pm2
#        run: |
#          pm2 restart 1
